version: 0.2

phases:
  install:
    run-as: root
    on-failure: ABORT
    commands:
      - echo "Installing dependencies"
      - npm install

  pre_build:
    run-as: root
    on-failure: ABORT
    commands:
      - echo "Pre-build phase"
      - echo "Generating Prisma client"
      - npx prisma generate
      - echo "Deploying Prisma migrations"
      - npx prisma migrate deploy

  build:
    run-as: root
    on-failure: ABORT
    commands:
      - echo "Building server"
      - npm run build

  post_build:
   run-as: root
   on-failure: ABORT
   commands:
      - echo "zip build artifact"
      - zip -r artifact.zip . -x "src/*"

artifacts:
  files:
    - artifact.zip